version: '3.8'

services:
  src_web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - src_postgres
      - redis
    networks:
      - common
    env_file:
      - .env

  src_postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - common
    ports:
      - "5433:5432"

  redis:
    image: "redis:alpine"
    networks:
      - common

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ../nginx/certbot/www:/var/www/certbot/:ro
      - ../nginx/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - src_web
      - certbot
    networks:
      - common
    restart: always
  
  certbot:
    image: certbot/certbot:latest
    command: renew
    # command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email sourabhsinha396@gmail.com --agree-tos --no-eff-email -d groupdiscussion.co -d www.groupdiscussion.co
    volumes:
      - ../nginx/certbot/www/:/var/www/certbot/:rw
      - ../nginx/certbot/conf/:/etc/letsencrypt/:rw

networks:
  common:
    external: true

volumes:
  postgres_data: