# Generated by Django 4.2.7 on 2023-11-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupdiscussions', '0002_alter_groupdiscussion_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('failed', 'failed'), ('pending', 'pending'), ('refunded', 'refunded')], max_length=10)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('extra', jsonfield.fields.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.couponcode')),
                ('group_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='groupdiscussions.groupdiscussion')),
                ('mentor', models.ForeignKey(help_text='Mentor or Moderator', on_delete=django.db.models.deletion.CASCADE, related_name='mentor_payments', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(help_text='User who paid', on_delete=django.db.models.deletion.CASCADE, related_name='mentee_payments', to=settings.AUTH_USER_MODEL)),
                ('refered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refered_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
