# Generated by Django 4.2.7 on 2023-12-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_referral_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refered_by',
        ),
        migrations.AlterField(
            model_name='credit',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='payments.payment'),
        ),
    ]
