# Generated by Django 4.2.7 on 2023-11-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='high_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
