# Generated by Django 4.2.7 on 2023-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='exam',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, to='blogs.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='exam',
            field=models.ManyToManyField(blank=True, to='blogs.exam'),
        ),
    ]
