# Generated by Django 4.2.7 on 2023-12-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupdiscussions', '0003_alter_groupdiscussion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdiscussion',
            options={'ordering': ('start_datetime',), 'verbose_name': 'Group Discussion', 'verbose_name_plural': 'Group Discussions'},
        ),
        migrations.AddField(
            model_name='groupdiscussion',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupdiscussion',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupdiscussion',
            name='meeting_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
