# Generated by Django 4.2.7 on 2023-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP Address', null=True)),
                ('utm_source', models.CharField(blank=True, help_text='UTM Source', max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM Medium', max_length=100, null=True)),
                ('referer_site', models.CharField(blank=True, help_text='Referrer Website URL', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hits',
            },
        ),
    ]
