# Generated by Django 4.2.7 on 2023-12-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='referer_site',
            field=models.CharField(blank=True, help_text='Referrer Website URL', max_length=255, null=True),
        ),
    ]
